services:
  py-cl:
    build:
      context: .
      dockerfile: py.Dockerfile
    image: py-service:latest
    depends_on:
      - expense
      - user
    networks:
      - app-network

  expense:
    build:
      context: .
      dockerfile: expense.Dockerfile
    image: expense-service:latest
    ports:
      - "8085:8085"
    networks:
      - app-network

  user:
    build:
      context: .
      dockerfile: user.Dockerfile
    image: user-service:latest
    ports:
      - "8090:8090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
