# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import expense_pb2 as expense__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in expense_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExpenseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddExpense = channel.unary_unary(
                '/expense.ExpenseService/AddExpense',
                request_serializer=expense__pb2.AddExpenseRequest.SerializeToString,
                response_deserializer=expense__pb2.ExpenseResponse.FromString,
                _registered_method=True)
        self.GetExpenses = channel.unary_unary(
                '/expense.ExpenseService/GetExpenses',
                request_serializer=expense__pb2.GetExpensesRequest.SerializeToString,
                response_deserializer=expense__pb2.ExpensesListResponse.FromString,
                _registered_method=True)


class ExpenseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddExpense(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExpenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpenseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddExpense': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExpense,
                    request_deserializer=expense__pb2.AddExpenseRequest.FromString,
                    response_serializer=expense__pb2.ExpenseResponse.SerializeToString,
            ),
            'GetExpenses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExpenses,
                    request_deserializer=expense__pb2.GetExpensesRequest.FromString,
                    response_serializer=expense__pb2.ExpensesListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'expense.ExpenseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('expense.ExpenseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpenseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddExpense(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/expense.ExpenseService/AddExpense',
            expense__pb2.AddExpenseRequest.SerializeToString,
            expense__pb2.ExpenseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExpenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/expense.ExpenseService/GetExpenses',
            expense__pb2.GetExpensesRequest.SerializeToString,
            expense__pb2.ExpensesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
