# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: expense.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'expense.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexpense.proto\x12\x07\x65xpense\"T\n\x11\x41\x64\x64\x45xpenseRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"5\n\x0f\x45xpenseResponse\x12\x12\n\nexpense_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"%\n\x12GetExpensesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\":\n\x14\x45xpensesListResponse\x12\"\n\x08\x65xpenses\x18\x01 \x03(\x0b\x32\x10.expense.Expense\"M\n\x07\x45xpense\x12\x12\n\nexpense_id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t2\x9f\x01\n\x0e\x45xpenseService\x12\x42\n\nAddExpense\x12\x1a.expense.AddExpenseRequest\x1a\x18.expense.ExpenseResponse\x12I\n\x0bGetExpenses\x12\x1b.expense.GetExpensesRequest\x1a\x1d.expense.ExpensesListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'expense_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDEXPENSEREQUEST']._serialized_start=26
  _globals['_ADDEXPENSEREQUEST']._serialized_end=110
  _globals['_EXPENSERESPONSE']._serialized_start=112
  _globals['_EXPENSERESPONSE']._serialized_end=165
  _globals['_GETEXPENSESREQUEST']._serialized_start=167
  _globals['_GETEXPENSESREQUEST']._serialized_end=204
  _globals['_EXPENSESLISTRESPONSE']._serialized_start=206
  _globals['_EXPENSESLISTRESPONSE']._serialized_end=264
  _globals['_EXPENSE']._serialized_start=266
  _globals['_EXPENSE']._serialized_end=343
  _globals['_EXPENSESERVICE']._serialized_start=346
  _globals['_EXPENSESERVICE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
